### ISSUE TITLE
tip标签有问题

### ISSUE THREAD

**Issue by aornus** [youngjuning/vscode-hexo-butterfly-tag-plugins-plus-snippets#1]
这个插件非常棒，弹出选项用起来很是方便❤。但是今天我在使用的时候发现了一个问题，就是当打出tip标签的时候，标签后边却自动补全成了`endnote`，就像这样，希望作者能修复下，辛苦了。
![image](https://github.com/youngjuning/vscode-hexo-butterfly-tag-plugins-plus-snippets/assets/69356310/8c34034d-ad45-4509-a252-cf5c78a19eb2)

**Comment by zisheng-ai** [comment]
> 这个插件非常棒，弹出选项用起来很是方便❤。但是今天我在使用的时候发现了一个问题，就是当打出tip标签的时候，标签后边却自动补全成了`endnote`，就像这样，希望作者能修复下，辛苦了。 ![image](https://user-images.githubusercontent.com/69356310/257461502-8c34034d-ad45-4509-a252-cf5c78a19eb2.png)

好的，周末更新一波
